name: Code Validations

on: pull_request

jobs:
  checking:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn install
      - name: TypeScript Check
        run: tsc
      - name: Lint Check
        run: yarn lint
